# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 378924e40e3a02cf8630f937af0c272e0f7576eb0c8e819e9cc2b5871084089a77910938cbde2bdb864e3b424cc86cfe9a3d9385358c04e1d35ff29209188183

test:
  secret_key_base: 4fb3065857822eb24c0071fbde34ea7fbf74abf27c0b24aaa707e20149b96ade1f12cc9d4c577c40c3fccee1976adee4908a49a45f720884e8b22393a64073c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
